name: CI (.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: .NET SDK version to use
        type: string
        default: "8.0.x"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - run: dotnet restore
      - run: dotnet format --verify-no-changes --no-restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
