name: CI (Python)

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to use
        type: string
        default: "3.12"
      working-directory:
        description: Working directory
        type: string
        default: "."

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"

      - run: pip install -r requirements.txt
      - run: ruff check .
      - run: black --check .
      - run: pytest
